version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: ci
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
    commit-message:
      prefix: ci
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: deps
