name: Release to pypi

on:
  release:
    types: [released]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/err-aprs-backend
    permissions:
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: Build package
        run: |
          uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
