name: Release to pypi

on:
  release:
    types: [released]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 2
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"

      - name: Install pip and poetry
        run: |
          pip install --upgrade --constraint .github/workflows/constraints.txt pip poetry
          pip --version
          poetry --version

      - name: Build package
        run: |
          poetry build

      - name: Publish package on PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.3
