# Runs after release-please creates a new release
# Builds and pushes the docker images for the release
name: Test building Docker Images
on:
  - push


jobs:
  build-dockerimage:
    name: Buld dockerimage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#registry-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
